stages:
  - test

before_script:
  - apt-get update
  - apt-get install -y python3 python3-pip
  - pip3 install pylint==3.2.5

test-code-formatted:
  stage: test
  script:
    # 1. Listar las herramientas instaladas en el runner
    - echo "Listing installed tools:"
    - apt list --installed
    - echo "Listing Pip libraries:"
    - pip list

    # 2. Test
    - echo "Testing code:"
    - pylint thoth/thoth.py

  only:
    - develop
  tags:
    - branch-develop
