stages:
  - build
  - test
  - deploy

before_script:
  - apt-get update -qq
  - apt-get install -y -qq python3 python3-pip curl unzip
  - pip3 install -r requirements.txt --quiet

build-frontend-app:
  stage: build
  script:
    - reflex export --frontend-only --no-zip
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == 'develop' || $CI_COMMIT_BRANCH == 'main'
  tags:
    - build-shared

format-code:
  stage: test
  script:
    - black thoth
    - pylint thoth
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == 'develop' || $CI_COMMIT_BRANCH == 'main'
  tags:
    - format-shared

pages:
  stage: deploy
  script:
    - reflex export --frontend-only --no-zip
    - mv .web/_static public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == 'develop' || $CI_COMMIT_BRANCH == 'main'
  tags:
    - deploy-shared
  environment: deployment
