stages:
  - build
  - test
  - deploy

before_script:
  - apt-get update -qq
  - apt-get install -y -qq python3 python3-pip
  - pip3 install -r requirements.txt --quiet

.build_script:
  script:
    - reflex export --frontend-only --no-zip

.formatting_script:
  script:
    - black thoth
    - pylint thoth

.deployment_script:
  script:
    - apt-get install -y unzip
    - reflex export --frontend-only --no-zip
    - mv .web/_static public

build-frontend-app:
  stage: build
  extends: .build_script
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == 'develop' || $CI_COMMIT_BRANCH == 'main'
  tags:
    - build-shared

format-code:
  stage: test
  extends: .formatting_script
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == 'develop' || $CI_COMMIT_BRANCH == 'main'
  tags:
    - format-shared

pages:
  stage: deploy
  extends: .deployment_script
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == 'develop' || $CI_COMMIT_BRANCH == 'main'
  tags:
    - deploy-shared
  environment: deployment
