stages:
  - test

before_script:
  - apt-get update -qq
  - apt-get install -y -qq python3 python3-pip
  - pip3 install -r requirements.txt --quiet

test-code-formatted:
  stage: test
  script:
    # 1. Listar las herramientas instaladas en el runner
    - echo "Listing installed tools:"
    - apt list --installed
    - echo "Listing Pip libraries:"
    - pip list

    # 2. Test
    - echo "Testing code in develop:"
    - pylint thoth/thoth.py
